version: '3.8'

services:
  postgres-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: wallet_admin
      POSTGRES_PASSWORD: SuperSecretPassword123!
      POSTGRES_DB: WalletLedgerDb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      
    cache:
    image: redis:alpine
    container_name: wallet_cache
    restart: always
    ports:
      - "6379:6379"

  wallet-api:
    build:
      context: .
      dockerfile: DigitalWalletAndLedgerAPI/Dockerfile 
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres-db;Database=WalletLedgerDb;Username=wallet_admin;Password=SuperSecretPassword123!
    depends_on:
      - postgres-db

volumes:
  pgdata: